version: '3.0'
services:
  mysql-master:
    image: mysql:${IMAGE_VERSION}
    container_name: mysql-master
    volumes:
      - ./data-master:/var/lib/mysql
      - ./mysqld-master:/var/run/mysqld
      - ./conf/my.cnf-master:/etc/my.cnf
    ports:
     - ${MASTER_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MASTER_PASSWORD}
    restart: always
    networks:
      mysql-cluster:
        aliases:
          - mysql-master

  mysql-slave:
    image: mysql:${IMAGE_VERSION}
    container_name: mysql-slave
    ports:
     - ${SLAVE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${SLAVE_PASSWORD}
    volumes:
      - ./data-slave:/var/lib/mysql
      - ./mysqld-slave:/var/run/mysqld
      - ./conf/my.cnf-slave:/etc/my.cnf
    restart: always
    networks:
      mysql-cluster:
        aliases:
          - mysql-slave

networks:
  mysql-cluster:
    name: mysql-cluster
    driver: bridge