global:
    resolve_timeout: 5m

route:
    receiver: "telegram-alert"
    group_wait: 10s
    group_interval: 30s
    repeat_interval: 1h

receivers:
    - name: "telegram-alert"
      telegram_configs:
          - bot_token: "${ALERTMANAGER_BOT_TOKEN}"
            chat_id: ${ALERTMANAGER_CHAT_ID}
            parse_mode: HTML
            message: |
                {{ if eq .Status "firing" }}
                <b>🚨 Alert Triggered</b>
                {{ range .Alerts }}
                <b>Summary:</b> {{ .Annotations.summary }}<br/>
                <b>Severity:</b> {{ .Labels.severity }}<br/>
                <b>Description:</b> {{ .Annotations.description }}<br/>
                <b>Instance:</b> {{ .Labels.instance }}<br/>
                <b>Start Time:</b> {{ .StartsAt }}<br/>
                {{ end }}
                {{ else if eq .Status "resolved" }}
                <b>✅ Alert Resolved</b>
                {{ range .Alerts }}
                <b>Summary:</b> {{ .Annotations.summary }}<br/>
                <b>Instance:</b> {{ .Labels.instance }}<br/>
                <b>Resolved At:</b> {{ .EndsAt }}<br/>
                {{ end }}
                {{ end }}
