version: '3.0'
services:
  mongodb:
    image: mongo:${IMAGE_VERSION}
    container_name: mongodb
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    command: --auth
    networks:
      mongo_net:
        aliases:
          - mongodb

networks:
  mongo_net:
    name: mongo_net
    driver: bridge