version: '3.5'
services:
  mysqld:
    image: mysql:8.0.30
    container_name: mysqld
    volumes:
      - ./data:/var/lib/mysql
      - ./mysqld:/var/run/mysqld
      - ./mysqld/log:/var/log/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always