version: '3.5'
services:
  mysqld:
    image: mysql:${IMAGE_VERSION}
    container_name: mysqld
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    restart: always