version: '3.5'
services:
  mysqld:
    image: mysql:5.7.27
    container_name: mysqld
    volumes:
      - ./data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always