groups:
    - name: SystemHealthAlerts
      rules:
          - alert: HighCPUUsage
            expr: avg(rate(node_cpu_seconds_total{mode="user"}[1m])) > 0.8
            for: 1m
            labels:
                severity: warning
            annotations:
                summary: "High CPU usage on {{ $labels.instance }}"
                description: "CPU usage is above 80% for more than 1 minute."

          - alert: LowDiskSpace
            expr: node_filesystem_free_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.1
            for: 2m
            labels:
                severity: critical
            annotations:
                summary: "Low disk space on {{ $labels.instance }}"
                description: "Disk space is less than 10%."
