services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      postgres_net:
        aliases:
          - postgres

networks:
  postgres_net:
    name: biz
    driver: bridge
