version: '3.5'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root #在此填写postgres的用户名
      POSTGRES_DB: w3tools #在此填写postgres的数据库名，默认是postgres
      POSTGRES_PASSWORD: root #在此填写postgres的数据库密码
    networks:
      biz:
        aliases:
          - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@w3tools.app #在此填写pgAdmin登录账户邮箱
      PGADMIN_DEFAULT_PASSWORD: admin@w3tools.app #在此填写pgAdmin密码
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      biz:
        aliases:
          - pgadmin

networks:
  biz:
    name: biz
    driver: bridge

